// Shared data model for the product catalog.
// Used by Lab 1 (API), Lab 2 (tests), and Lab 4 (React component).
export interface Product {
  id: number;
  name: string;
  price: number;
  category?: string;
}

// Creation payload (id is auto-generated by the server).
export type NewProduct = Omit<Product, "id">;
